#!/usr/bin/env python

import pynotify
import sys
import os
import glib

def install_cb(n, action):
   assert action == "install"
   n.close()
   os.execlp("liveinst", "liveinst")

if __name__ == '__main__':
    if not pynotify.init("Install Fedora"):
        sys.exit(1)

    n = pynotify.Notification("Install Fedora",
        "You are currently using an uninstalled live image.\n" +
        "If you want to keep using Fedora, you can install " +
        "it to your hard disk.",
        "anaconda");

    n.add_action("install", "Install", install_cb)
    n.set_hint("resident", True)

    if not n.show():
        print "Failed to send notification"
        sys.exit(1)

    glib.MainLoop().run()
